# Generated by Django 3.2.7 on 2021-09-07 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=150, verbose_name='INVOICE No.')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('consignee_name', models.CharField(blank=True, max_length=150, verbose_name='名前（Consignee）')),
                ('consignee_address', models.CharField(blank=True, max_length=500, verbose_name='住所（Consignee）')),
                ('consignee_tel', models.CharField(blank=True, max_length=150, verbose_name='電話番号（Consignee）')),
                ('consignee_fax', models.CharField(blank=True, max_length=150, verbose_name='FAX（Consignee）')),
                ('shipped_per', models.CharField(blank=True, max_length=150, verbose_name='Shipped_per')),
                ('on_or_about', models.CharField(blank=True, max_length=150, verbose_name='On or About')),
                ('to', models.CharField(blank=True, max_length=150, verbose_name='To')),
                ('final_destination', models.CharField(blank=True, max_length=150, verbose_name='Final Destination')),
                ('payment_terms', models.CharField(blank=True, default='100% before due date by Bank Transfer', max_length=150, verbose_name='Payment Terms')),
                ('payment_due', models.DateField(verbose_name='Payment Due')),
                ('bank_account', models.TextField(blank=True, verbose_name='Bank Account')),
                ('beneficiary_info_name', models.CharField(blank=True, max_length=150, verbose_name='Name（Beneficiarys Information）')),
                ('beneficiary_info_address', models.CharField(blank=True, max_length=150, verbose_name='Address（Beneficiarys Information）')),
                ('beneficiary_info_tel', models.CharField(blank=True, max_length=150, verbose_name='Tel（Beneficiarys Information）')),
                ('item_description', models.TextField(blank=True, verbose_name='Item Description')),
                ('insurance', models.CharField(blank=True, max_length=150, verbose_name='Insurance')),
                ('total_price', models.CharField(blank=True, max_length=150, verbose_name='Total Price')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='作成日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
