# Generated by Django 3.2.7 on 2022-05-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Notify_Party',
            field=models.CharField(blank=True, max_length=150, verbose_name='Notify_Party'),
        ),
    ]
