# Generated by Django 3.2.7 on 2022-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_notify_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Notify_Party',
            field=models.TextField(blank=True, verbose_name='Notify_Party'),
        ),
    ]
